//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public int CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEname { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerTel1 { get; set; }
        public string CustomerTel2 { get; set; }
        public string CountryName { get; set; }
        public string TownName { get; set; }
        public string Email { get; set; }
    }
}
