//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCode
    {
        public int Serial { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Id { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string DescName { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public Nullable<int> CountrySerial { get; set; }
        public Nullable<int> TownSerial { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    
        public virtual CountryCode CountryCode { get; set; }
        public virtual TownCode TownCode { get; set; }
    }
