//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealersData
    {
        public int DealerCode { get; set; }
        public string DealerName { get; set; }
        public string DealerEname { get; set; }
        public string DealerAddress1 { get; set; }
        public string DealerTel1 { get; set; }
        public string DealerTel2 { get; set; }
        public string CountryName { get; set; }
        public string TownName { get; set; }
        public string Email { get; set; }
    }
}
