//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesData
    {
        public int EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEname { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeTel1 { get; set; }
        public string EmployeeTel2 { get; set; }
        public string CountryName { get; set; }
        public string TownName { get; set; }
        public string Email { get; set; }
    }
}
