//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        public int Serial { get; set; }
        public Nullable<int> Code { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string DescName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SerialGroup { get; set; }
        public Nullable<int> Unit1 { get; set; }
        public Nullable<int> Unit2 { get; set; }
        public Nullable<int> Unit3 { get; set; }
        public Nullable<double> PricePurchase1Unit1 { get; set; }
        public Nullable<double> PricePurchase1Unit2 { get; set; }
        public Nullable<double> PriceSale1Unit1 { get; set; }
        public Nullable<double> PriceSale1Unit2 { get; set; }
        public Nullable<double> Counts { get; set; }
    
        public virtual GroupCode GroupCode { get; set; }
        public virtual UnitCode UnitCode { get; set; }
    }
}
