//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCode()
        {
            this.HPurchase = new HashSet<HPurchase>();
            this.HSales = new HashSet<HSales>();
        }
    
        public int Serial { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> Code { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string DescName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SerialGroup { get; set; }
        public Nullable<int> Unit1 { get; set; }
        public Nullable<int> Unit2 { get; set; }
        public Nullable<int> Unit3 { get; set; }
        public Nullable<double> PricePurchase1Unit1 { get; set; }
        public Nullable<double> PricePurchase1Unit2 { get; set; }
        public Nullable<double> PriceSale1Unit1 { get; set; }
        public Nullable<double> PriceSale1Unit2 { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<double> Counts { get; set; }
    
        public virtual GroupCode GroupCode { get; set; }
        public virtual StoreCode StoreCode { get; set; }
        public virtual UnitCode UnitCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HPurchase> HPurchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HSales> HSales { get; set; }
    }

