//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCard
    {
        public int ItemCode { get; set; }
        public Nullable<int> ItemCode2 { get; set; }
        public string ItemName { get; set; }
        public string ItemEName { get; set; }
        public string ItemDescName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPurchase1Unit1 { get; set; }
        public Nullable<double> ItemPurchase1Unit2 { get; set; }
        public Nullable<double> ItemSales1Unit1 { get; set; }
        public Nullable<double> ItemSales1Unit2 { get; set; }
        public Nullable<int> Unit1 { get; set; }
        public Nullable<int> Unit2 { get; set; }
        public Nullable<int> Unit3 { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public Nullable<int> GroupCode2 { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupColorName { get; set; }
        public Nullable<int> UnitCode { get; set; }
        public Nullable<int> UnitCode2 { get; set; }
        public string UnitName { get; set; }
        public string UnitDescription { get; set; }
        public Nullable<int> HpurchaseCode { get; set; }
        public Nullable<int> HpurchaseCode2 { get; set; }
        public Nullable<int> HpurchaseCurrency { get; set; }
        public Nullable<System.DateTime> HpurchaseDate { get; set; }
        public Nullable<int> HpurchaseDealerCode { get; set; }
        public Nullable<double> HpurchaseDiscount { get; set; }
        public Nullable<double> HpurchaseDiscValue { get; set; }
        public Nullable<double> HpurchaseFactor { get; set; }
        public Nullable<double> HpurchasePrice { get; set; }
        public Nullable<double> HpurchaseQuantity { get; set; }
        public Nullable<double> HpurchaseTax { get; set; }
        public Nullable<double> HpurchaseTotal { get; set; }
        public Nullable<double> HpurchaseTotalAfter { get; set; }
        public Nullable<int> HSalesCode { get; set; }
        public Nullable<int> HSalesCode2 { get; set; }
        public Nullable<int> HSalesCurrency { get; set; }
        public Nullable<System.DateTime> HSalesDate { get; set; }
        public Nullable<int> HSalesDealerCode { get; set; }
        public Nullable<double> HSalesDiscount { get; set; }
        public Nullable<double> HSalesDiscValue { get; set; }
        public Nullable<double> HSalesFactor { get; set; }
        public Nullable<double> HSalesPrice { get; set; }
        public Nullable<double> HSalesQuantity { get; set; }
        public Nullable<double> HSalesTax { get; set; }
        public Nullable<double> HSalesTotal { get; set; }
        public Nullable<double> HSalesTotalAfter { get; set; }
    }
}
