//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptCustomers
    {
        public int CustomerCode { get; set; }
        public Nullable<int> CustomerCode2 { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEname { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerTel1 { get; set; }
        public string CustomerTel2 { get; set; }
        public string Telephone3 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryCode2 { get; set; }
        public string CountryName { get; set; }
        public string CountryEName { get; set; }
        public string CountryDescName { get; set; }
        public string CountryNotes { get; set; }
        public Nullable<int> TownCode { get; set; }
        public Nullable<int> TownCode2 { get; set; }
        public string TownName { get; set; }
        public string TownEname { get; set; }
        public string TownDescname { get; set; }
        public string Townnotes { get; set; }
    }
}
