//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptDealers
    {
        public int DealerCode { get; set; }
        public Nullable<int> DealerCode2 { get; set; }
        public string DealerName { get; set; }
        public string DealerEname { get; set; }
        public string DealerAddress1 { get; set; }
        public string DealerAddress2 { get; set; }
        public string DealerTel1 { get; set; }
        public string DealerTel2 { get; set; }
        public string Telephone3 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryCode2 { get; set; }
        public string CountryName { get; set; }
        public string CountryEName { get; set; }
        public string CountryDescName { get; set; }
        public string CountryNotes { get; set; }
        public Nullable<int> TownCode { get; set; }
        public Nullable<int> TownCode2 { get; set; }
        public string TownName { get; set; }
        public string TownEname { get; set; }
        public string TownDescname { get; set; }
        public string Townnotes { get; set; }
        public Nullable<int> hsalesCode { get; set; }
        public Nullable<int> HsalesCode2 { get; set; }
        public Nullable<int> HsalesCurrency { get; set; }
        public Nullable<System.DateTime> HsalesDate { get; set; }
        public Nullable<int> HsalesDealerCode { get; set; }
        public Nullable<double> HsalesDiscount { get; set; }
        public Nullable<double> HsalesDiscValue { get; set; }
        public Nullable<double> HsalesFactor { get; set; }
        public Nullable<double> HsalesPrice { get; set; }
        public Nullable<double> HsalesQuantity { get; set; }
        public Nullable<double> FirstPayment { get; set; }
        public Nullable<double> HsalesTax { get; set; }
        public Nullable<double> HsalesTotal { get; set; }
        public Nullable<double> HsalesTotalAfter { get; set; }
        public Nullable<int> HpurchaseCode { get; set; }
        public Nullable<int> HpurchaseCode2 { get; set; }
        public Nullable<int> HpurchaseCurrency { get; set; }
        public Nullable<System.DateTime> HpurchaseDate { get; set; }
        public Nullable<int> HpurchaseDealerCode { get; set; }
        public Nullable<double> HpurchaseDiscount { get; set; }
        public Nullable<double> HpurchaseDiscValue { get; set; }
        public Nullable<double> HpurchaseFactor { get; set; }
        public Nullable<double> HpurchasePrice { get; set; }
        public Nullable<double> HpurchaseQuantity { get; set; }
        public Nullable<double> HpurchaseTax { get; set; }
        public Nullable<double> HpurchaseTotal { get; set; }
        public Nullable<double> HpurchaseTotalAfter { get; set; }
    }
}
