//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptPurchase
    {
        public Nullable<int> ItemCode { get; set; }
        public Nullable<int> ItemCode2 { get; set; }
        public string ItemName { get; set; }
        public string ItemEName { get; set; }
        public string ItemDescName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPurchase1Unit1 { get; set; }
        public Nullable<double> ItemPurchase1Unit2 { get; set; }
        public Nullable<double> ItemSales1Unit1 { get; set; }
        public Nullable<double> ItemSales1Unit2 { get; set; }
        public Nullable<int> Unit1 { get; set; }
        public Nullable<int> Unit2 { get; set; }
        public Nullable<int> Unit3 { get; set; }
        public int HpurchaseCode { get; set; }
        public Nullable<int> HpurchaseCode2 { get; set; }
        public Nullable<int> HpurchaseCurrency { get; set; }
        public Nullable<System.DateTime> HpurchaseDate { get; set; }
        public Nullable<double> HpurchaseDiscount { get; set; }
        public Nullable<double> HpurchaseDiscValue { get; set; }
        public Nullable<double> HpurchaseFactor { get; set; }
        public Nullable<double> HpurchasePrice { get; set; }
        public Nullable<double> HpurchaseQuantity { get; set; }
        public Nullable<double> HpurchaseTax { get; set; }
        public Nullable<double> HpurchaseTotal { get; set; }
        public Nullable<double> HpurchaseTotalAfter { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public Nullable<int> GroupCode2 { get; set; }
        public string GroupName { get; set; }
        public string GroupEName { get; set; }
        public string GroupDescName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupColorName { get; set; }
        public Nullable<int> UnitCode { get; set; }
        public Nullable<int> UnitCode2 { get; set; }
        public string UnitName { get; set; }
        public string UnitEName { get; set; }
        public string UnitDescName { get; set; }
        public string UnitDescription { get; set; }
        public Nullable<int> StoreCode { get; set; }
        public Nullable<int> StoreCode2 { get; set; }
        public string StoreName { get; set; }
        public string StoreEName { get; set; }
        public string StoreDescName { get; set; }
        public string StoreDescription { get; set; }
        public Nullable<int> StoreNumLeans { get; set; }
        public string StoreAddress { get; set; }
        public string StoreArea { get; set; }
        public string StorePhone1 { get; set; }
        public string StorePhone2 { get; set; }
        public string StorePhone3 { get; set; }
        public string StorePhone4 { get; set; }
        public string StoreKeeper { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public Nullable<int> SupplierCode2 { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEName { get; set; }
        public string SupplierDescName { get; set; }
        public string SupplierAddress1 { get; set; }
        public string SupplierAddress2 { get; set; }
        public Nullable<int> DealerCode { get; set; }
        public Nullable<int> DealerCode2 { get; set; }
        public string DealerName { get; set; }
        public string DealerEName { get; set; }
        public string DealerDescName { get; set; }
        public string DealerAddress1 { get; set; }
        public string DealerAddress2 { get; set; }
    }
}
