//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptStore
    {
        public int StoreCode { get; set; }
        public Nullable<int> StoreCode2 { get; set; }
        public string StoreName { get; set; }
        public string StoreDescription { get; set; }
        public string StoreAddress { get; set; }
        public string StoreArea { get; set; }
        public string StorePhone1 { get; set; }
        public string StorePhone2 { get; set; }
        public string StorePhone3 { get; set; }
        public string StorePhone4 { get; set; }
        public Nullable<int> EmployeeCode { get; set; }
        public string EmployeeCode2 { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEName { get; set; }
        public string EmployeeDescName { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryCode2 { get; set; }
        public string CountryName { get; set; }
        public string CountryNotes { get; set; }
        public Nullable<int> TownCode { get; set; }
        public Nullable<int> TownCode2 { get; set; }
        public string TownName { get; set; }
        public string Townnotes { get; set; }
    }
}
