//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptSuppliers
    {
        public int SupplierCode { get; set; }
        public Nullable<int> SupplierCode2 { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEname { get; set; }
        public string SupplierAddress1 { get; set; }
        public string SupplierAddress2 { get; set; }
        public string SupplierTel1 { get; set; }
        public string SupplierTel2 { get; set; }
        public string Telephone3 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryCode2 { get; set; }
        public string CountryName { get; set; }
        public string CountryNotes { get; set; }
        public Nullable<int> TownCode { get; set; }
        public Nullable<int> TownCode2 { get; set; }
        public string TownName { get; set; }
        public string Townnotes { get; set; }
    }
}
