//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Collections.Generic;
    
    public partial class RptSales
    {
        public int Code { get; set; }
        public Nullable<int> ItCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> StCode { get; set; }
        public string StoreName { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> Total { get; set; }
    }

