//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersData
    {
        public int SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEname { get; set; }
        public string SupplierAddress1 { get; set; }
        public string SupplierTel1 { get; set; }
        public string SupplierTel2 { get; set; }
        public string CountryName { get; set; }
        public string TownName { get; set; }
        public string Email { get; set; }
    }
}
