//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAccount
    {
        public Nullable<int> SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public Nullable<double> ToatalPurchase { get; set; }
    }
}
